//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS3BackupApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___コピー {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___コピー() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS3BackupApp.Properties.Resources - コピー", typeof(Resources___コピー).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complite_Backup {
            get {
                return ResourceManager.GetString("Complite_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   復元が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complite_Restore {
            get {
                return ResourceManager.GetString("Complite_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このプロファイルに保存されているセーブデータもすべて削除されます。
        ///プロファイルを削除しますか？
        ///
        ///プロファイル: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_DeleteProfile {
            get {
                return ResourceManager.GetString("Confirm_DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このセーブデータを削除しますか？
        ///
        ///セーブデータ: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_DeleteSavedata {
            get {
                return ResourceManager.GetString("Confirm_DeleteSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしますか？
        ///
        ///セーブデータ: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_Overwrite {
            get {
                return ResourceManager.GetString("Confirm_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このセーブデータを復元しますか？
        ///
        ///セーブデータ: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_Restore {
            get {
                return ResourceManager.GetString("Confirm_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なパスが指定されました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentPath {
            get {
                return ResourceManager.GetString("Error_ArgumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダのパスが長すぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BackupPathTooLong {
            get {
                return ResourceManager.GetString("Error_BackupPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダのパスが長すぎるため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BackupPathTooLongForAuto {
            get {
                return ResourceManager.GetString("Error_BackupPathTooLongForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのコピー中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CopyEx {
            get {
                return ResourceManager.GetString("Error_CopyEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダの作成中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateDirectoryEx {
            get {
                return ResourceManager.GetString("Error_CreateDirectoryEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダの作成中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateEx {
            get {
                return ResourceManager.GetString("Error_CreateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの作成中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateFileEx {
            get {
                return ResourceManager.GetString("Error_CreateFileEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダの削除中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DeleteEx {
            get {
                return ResourceManager.GetString("Error_DeleteEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリが存在しません。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyBackupPath {
            get {
                return ResourceManager.GetString("Error_EmptyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダが選択されていないため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyBackupPathForAuto {
            get {
                return ResourceManager.GetString("Error_EmptyBackupPathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを選択するか入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyProfile {
            get {
                return ResourceManager.GetString("Error_EmptyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブ名を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptySavename {
            get {
                return ResourceManager.GetString("Error_EmptySavename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが存在しません。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリの取得中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_GetDirectoriesEx {
            get {
                return ResourceManager.GetString("Error_GetDirectoriesEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダの更新日時の取得中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_GetLastWriteTimeEx {
            get {
                return ResourceManager.GetString("Error_GetLastWriteTimeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたバックアップフォルダのパスは無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPath {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたバックアップフォルダのパスに無効な文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathChars {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたバックアップフォルダのパスに無効な文字が含まれているため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathCharsForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathCharsForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたバックアップフォルダのパスは無効のため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたアイテムのフォーマットが正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidFormat {
            get {
                return ResourceManager.GetString("Error_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータのフォルダのパスが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePath {
            get {
                return ResourceManager.GetString("Error_InvalidSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータのフォルダのパスに無効な文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathChars {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータのフォルダのパスに無効な文字が含まれているため、自動バックアップを実行できませんでした。。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathCharsForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathCharsForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータのフォルダのパスが無効のため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O エラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_IO {
            get {
                return ResourceManager.GetString("Error_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモファイルの作成中にエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoCreateEx {
            get {
                return ResourceManager.GetString("Error_MemoCreateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモの読み込み中にエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoReadEx {
            get {
                return ResourceManager.GetString("Error_MemoReadEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモを読み込めませんでした。
        ///バックアップフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoReadNoBackupPath {
            get {
                return ResourceManager.GetString("Error_MemoReadNoBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモが保存されませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWrite {
            get {
                return ResourceManager.GetString("Error_MemoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモが保存されませんでした。
        ///バックアップフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWriteEmptyBackupPath {
            get {
                return ResourceManager.GetString("Error_MemoWriteEmptyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモの保存中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWriteEx {
            get {
                return ResourceManager.GetString("Error_MemoWriteEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MoveEx {
            get {
                return ResourceManager.GetString("Error_MoveEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に使われている名前です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Error_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoItemSelected {
            get {
                return ResourceManager.GetString("Error_NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラー: セーブデータの保存フォルダが未設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoSavePath {
            get {
                return ResourceManager.GetString("Error_NoSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたアカウントのセーブデータが見つかりませんでした。
        ///アカウントを選び直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundAccount {
            get {
                return ResourceManager.GetString("Error_NotFoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundBackupfolder {
            get {
                return ResourceManager.GetString("Error_NotfoundBackupfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダが存在しないため、自動バックアップを実行できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundBackupfolderForAuto {
            get {
                return ResourceManager.GetString("Error_NotfoundBackupfolderForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundMemo {
            get {
                return ResourceManager.GetString("Error_NotFoundMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップされたセーブデータが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundSavedata {
            get {
                return ResourceManager.GetString("Error_NotFoundSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータの保存フォルダが見つかりませんでした。
        ///ゲームを起動してセーブデータを作成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundSavefolder {
            get {
                return ResourceManager.GetString("Error_NotfoundSavefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブデータの保存フォルダが見つからなかったため、自動バックアップを実行できませんでした。
        ///ゲームを起動してセーブデータを作成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundSavefolderForAuto {
            get {
                return ResourceManager.GetString("Error_NotfoundSavefolderForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サポートされていないパス形式です。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotSupportedPath {
            get {
                return ResourceManager.GetString("Error_NotSupportedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスが長すぎます。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_PathTooLong {
            get {
                return ResourceManager.GetString("Error_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セキュリティ許可が不足しています。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Security {
            get {
                return ResourceManager.GetString("Error_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダの更新日時の変更中に予期しないエラーが発生しました。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_SetLastWriteTimeEx {
            get {
                return ResourceManager.GetString("Error_SetLastWriteTimeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクセス権限がありません。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Error_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form_ChangeName {
            get {
                return ResourceManager.GetString("Form_ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するアカウント: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Account {
            get {
                return ResourceManager.GetString("Info_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} から {1} に名前を変更しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Rename {
            get {
                return ResourceManager.GetString("Info_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ欄
        ///セーブデータを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_SelectSavedata {
            get {
                return ResourceManager.GetString("Info_SelectSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい名前を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_EnterNewName {
            get {
                return ResourceManager.GetString("Prompt_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定の保存中にエラーが発生しました。
        ///このまま終了すると設定が失われる可能性があります。
        ///もう一度保存を試みますか？
        ///
        ///エラー内容: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning_Close {
            get {
                return ResourceManager.GetString("Warning_Close", resourceCulture);
            }
        }
    }
}
